spring:
  application:
    name: CPNVisualSystem
  profiles:
    active: dev  # 默认启用 dev 环境

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.cpnvisualsystem.entity

server:
  port: 8080

logging:
  level:
    com.baomidou: INFO
    com.alibaba: INFO
